### ISSUE TITLE
處理 ESlint，Prettier 設定

### ISSUE THREAD

**Issue by ayugioh2003** [ayugioh2003/psystore#2]
用 vue cli 3+ 新開一個專案時，eslint 沒問題
但自己添加 prettier 設定時，卻一直失敗 QQ

ESlint 設定
* [comma-dangle - Rules - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/rules/comma-dangle)
* [List of available rules - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/rules/)

prettier 設定
* [Options · Prettier](https://prettier.io/docs/en/options.html)

相關記錄
* [vue cli + eslint + prettier 設定・Issue #194・ayugioh2003/today-i-learned](https://github.com/ayugioh2003/today-i-learned/issues/194)

**Comment by ayugioh2003** [comment]
後來發現是檔名打錯了… orz
檔名最前面要加上一個 `.`
加上之後 prettier 就正常運作了

```yaml
# .prettierrc.yaml
# printWidth: 80
tabWidth: 2
# semi: false
singleQuote: true
trailingComma: 'es5'
# bracketSpacing: true
arrowParens: 'always' # 'avoid'
```
