### ISSUE TITLE
自動佈署 github actions

### ISSUE THREAD

**Issue by ayugioh2003** [ayugioh2003/psystore#34]
* [深入但不淺出，如何用 github actions 自動發佈 gh-pages - Milk Midi - Medium](https://medium.com/@milkmidi/深入但不淺出-如何用-github-actions-自動發佈-gh-pages-8183464dfe84)
* [milkmidi/The-F2E---Rapid-Chat](https://github.com/milkmidi/The-F2E---Rapid-Chat)

```
name: deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : githubaction
      USER_EMAIL  : githubaction@fake.com
      PUBLISH_DIR : ./dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: git config
        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
    - name: deploy to gh-pages
      run: |
        npm run gh
        echo 🤘 deploy gh-pages complete.        
```

**Comment by ayugioh2003** [comment]
* [Deploy to GitHub Pages · Actions · GitHub Marketplace](https://github.com/marketplace/actions/deploy-to-github-pages)
* [sdras/awesome-actions: A curated list of awesome actions to use on GitHub](https://github.com/sdras/awesome-actions)

```
name: Build and Deploy # test 2020-05-10 01:25:31
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
```
